hyperskill_project:
  id: 208
  ide_files: https://stepik.org/media/attachments/lesson/589093/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Mon, 06 Feb 2023 05:22:19 UTC"
stages:
- id: 1039
  step: 15810
  is_completed: false
- id: 1040
  step: 15811
  is_completed: false
- id: 1041
  step: 15812
  is_completed: false
- id: 1042
  step: 15813
  is_completed: false
- id: 1043
  step: 15814
  is_completed: false
topics:
  0:
  - title: Computer algorithms
    theory_id: 16547
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Taking input
    theory_id: 5913
  - title: Naming variables
    theory_id: 5885
  - title: Program with numbers
    theory_id: 5872
  - title: If statement
    theory_id: 5953
  - title: Else statement
    theory_id: 5932
  - title: Load module
    theory_id: 6019
  - title: For loop
    theory_id: 6065
  - title: While loop
    theory_id: 5940
  - title: Loop control statements
    theory_id: 6302
  - title: Elif statement
    theory_id: 5926
  - title: Program execution
    theory_id: 6047
  - title: Errors
    theory_id: 6052
  - title: Exceptions
    theory_id: 6042
  - title: Built-in exceptions
    theory_id: 11680
  - title: Exception handling
    theory_id: 6270
  - title: Flowcharts
    theory_id: 14976
  - title: Basic data types
    theory_id: 5852
  - title: Variables
    theory_id: 5859
  - title: Invoking a function
    theory_id: 5891
  - title: Integer arithmetic
    theory_id: 5865
  - title: List
    theory_id: 5979
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: Basic string methods
    theory_id: 6842
  - title: Type casting
    theory_id: 6224
  - title: Escape sequences
    theory_id: 7130
  - title: Split and join
    theory_id: 6972
  3:
  - title: Declaring a function
    theory_id: 5900
  - title: Scopes
    theory_id: 6322
